stages: 
    - lint
    - test
    - e2e

lint:
    stage: lint
    image: node:20
    before_script:
        - npm ci
    script:
        - npm run lint
    artifacts:
        expire_in: 1 hr

test:
    stage: test
    image: node:20
    before_script:
        - npm ci
    script:
        - npm test
    artifacts:
        expire_in: 1 hr

e2e:
    stage: e2e
    image: mcr.microsoft.com/playwright:v1.52.0-jammy
    before_script:
        - npm ci
    script:
        - npx playwright test --project=chromium
    artifacts:
        paths:
         - playwright-report/
        expire_in: 1 hr
